from __future__ import annotations

from pathlib import Path
import unittest


STATIC = Path(__file__).resolve().parents[1] / "static"


class MobileAssistiveNavigationTests(unittest.TestCase):
    def test_mobile_navigation_uses_assistive_controls(self) -> None:
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        self.assertIn('id="assistive-nav"', html)
        self.assertIn('id="assistive-menu"', html)
        self.assertIn('id="assistive-toggle"', html)
        self.assertIn('id="assistive-toggle-badge"', html)
        self.assertIn('id="assistive-message-badge"', html)
        self.assertNotIn('class="bottom-nav"', html)
        self.assertIn('aria-expanded="false"', html)
        self.assertNotIn('data-version-switch', html)
        self.assertNotIn('切换到 Next 版', html)

    def test_drag_memory_keyboard_and_viewport_support_are_present(self) -> None:
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        self.assertIn("mobileAssistiveNavPositionV1", script)
        self.assertIn("setPointerCapture", script)
        self.assertIn("visualViewport", script)
        self.assertIn("keyboard-hidden", script)
        self.assertIn("async function route(){closeAssistiveMenu();const path=appPath()", script)
        self.assertIn("function appPath(){return location.pathname||'/'}", script)
        self.assertIn("location.search", script)
        self.assertIn("target.pathname+target.search+target.hash", script)

    def test_desktop_keeps_sidebar_and_hides_assistive_navigation(self) -> None:
        css = (STATIC / "style.css").read_text(encoding="utf-8")
        self.assertIn("@media(min-width:920px){.assistive-nav{display:none}", css)
        self.assertIn(".assistive-nav.side-right", css)
        self.assertIn("safe-area-inset-right", css)

    def test_unread_messages_mark_the_assistive_button_and_message_item(self) -> None:
        script = (STATIC / "chat.js").read_text(encoding="utf-8")
        css = (STATIC / "chat-redesign.css").read_text(encoding="utf-8")
        self.assertIn("function updateUnreadIndicators", script)
        self.assertIn("['#assistive-toggle-badge','#assistive-message-badge']", script)
        self.assertIn("updateUnreadIndicators(count)", script)
        self.assertIn("updateUnreadIndicators(chat.overview.unread)", script)
        self.assertIn('.assistive-unread-dot[hidden]{display:none!important}', css)

    def test_rerun_reset_and_stop_controls_are_present(self) -> None:
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        self.assertIn('id="global-task-stop"', html)
        self.assertIn("function resetCreatePage()", script)
        self.assertIn("rerunLoadToken", script)
        self.assertIn("/cancel`,{method:'POST'}", script)
        self.assertIn("if(wasRerun)resetCreatePage()", script)

    def test_desktop_result_gallery_and_persistent_comparison_are_present(self) -> None:
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "style.css").read_text(encoding="utf-8")
        guard = (STATIC / "mobile-media-guard.js").read_text(encoding="utf-8")
        self.assertIn('id="detail-lightbox"', html)
        self.assertIn("function renderDesktopGallery", script)
        self.assertIn("const detailDesktopMedia=window.matchMedia('(min-width:1100px)')", script)
        self.assertIn("function desktopDetailMode(){return detailDesktopMedia.matches}", script)
        self.assertIn("detailDesktopMedia.addEventListener('change'", script)
        self.assertIn("state.comparisons[stateKey]", script)
        self.assertIn(".desktop-result-gallery", css)
        self.assertIn("grid-template-columns:repeat(auto-fit,minmax(120px,1fr))", css)
        self.assertIn(".side-nav{position:fixed", css)
        self.assertIn("'(max-width:1099px)'", guard)
        self.assertIn("'detail-lightbox'", guard)
        self.assertIn("dialogPrototype.showModal=function", guard)

    def test_detail_workspace_paging_and_mobile_controls_are_present(self) -> None:
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "style.css").read_text(encoding="utf-8")
        self.assertIn('id="detail-workspace"', html)
        self.assertIn('id="detail-lightbox-prev"', html)
        self.assertIn('id="detail-lightbox-next"', html)
        self.assertIn("function installMobileMediaControls", script)
        self.assertIn("scheduleMobileMediaControls", script)
        self.assertIn("items.length-1", script)
        self.assertIn("suppressClickUntil=0", script)
        self.assertIn("requestAnimationFrame(flushPan)", script)
        self.assertIn("viewport.classList.add('panning')", script)
        self.assertIn(".detail-lightbox-stage.panning", css)
        self.assertIn(".detail-workspace{grid-template-columns", css)
        self.assertIn(".mobile-controls-card.mobile-controls-visible", css)

    def test_formal_mobile_media_detail_handles_images_and_video(self) -> None:
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "interface.css").read_text(encoding="utf-8")
        icons = (STATIC / "icons.js").read_text(encoding="utf-8")
        self.assertNotIn('id="photo-detail-experience-toggle"', html)
        self.assertNotIn('高清历史详情（体验模式）', html)
        self.assertIn('id="photo-detail-stage"', html)
        self.assertIn('id="photo-detail-track"', html)
        self.assertEqual(html.count('data-photo-slot="'), 5)
        self.assertIn('id="photo-detail-info-sheet"', html)
        self.assertIn('id="photo-detail-action-sheet"', html)
        self.assertIn('id="photo-detail-delete-menu"', html)
        self.assertIn('id="photo-detail-delete-image"', html)
        self.assertIn('id="photo-detail-delete-task"', html)
        self.assertLess(html.index('id="photo-detail-delete-task"'), html.index('id="photo-detail-delete-image"'))
        self.assertIn('id="photo-detail-video-controls"', html)
        self.assertIn('id="photo-detail-video-seek"', html)
        self.assertIn('id="photo-detail-video-play"', html)
        self.assertIn('id="photo-detail-video-mute"', html)
        self.assertIn('id="photo-detail-video-elapsed"', html)
        self.assertIn('id="photo-detail-video-remaining"', html)
        self.assertNotIn('id="photo-detail-video-fullscreen"', html)
        self.assertIn('class="photo-detail-action-group photo-detail-action-group-left"', html)
        self.assertIn('class="photo-detail-action-group photo-detail-action-group-right"', html)
        topbar_start = html.index('class="photo-detail-topbar"')
        self.assertLess(html.index('id="photo-detail-actions"', topbar_start), html.index('</header>', topbar_start))
        self.assertEqual(html.count('class="photo-detail-sheet-grabber"'), 2)
        self.assertEqual(html.count('class="photo-detail-sheet-dimmer"'), 2)
        self.assertNotIn('data-photo-sheet-close', html)
        self.assertNotIn("PHOTO_DETAIL_SETTING_KEY", script)
        self.assertIn("function photoDetailMobileMode(){return matchMedia('(max-width:1099px)').matches}", script)
        self.assertIn("function photoDetailFormalEligible(job){return photoDetailMobileMode()}", script)
        self.assertIn("function photoDetailMediaItems(job)", script)
        self.assertIn("function photoDetailVersionIsVideo", script)
        self.assertIn("function photoDetailRenderMediaVideo", script)
        self.assertIn("function photoDetailPauseInactiveVideos", script)
        self.assertIn("video.controls=false", script)
        self.assertIn("video.playsInline=true", script)
        self.assertIn("video.preload=primary?'metadata':'none'", script)
        self.assertIn("h3VideoPosterUrl(entry.job,entry.item)", script)
        self.assertIn("photoDetailVideoPositions:new Map()", script)
        self.assertIn("function photoDetailVideoBind", script)
        self.assertIn("function photoDetailVideoUnbind", script)
        self.assertIn("function photoDetailVideoSeekInput", script)
        self.assertIn("function photoDetailVideoSeekCommit", script)
        self.assertIn("function photoDetailVideoSeekAt", script)
        self.assertIn("function photoDetailVideoSeekPointerDown", script)
        self.assertIn("function photoDetailVideoSeekPointerMove", script)
        self.assertIn("function photoDetailVideoSeekPointerEnd", script)
        self.assertIn("videoSeekZone.setPointerCapture", script)
        self.assertIn("videoSeekZone.addEventListener('pointercancel'", script)
        self.assertIn("videoSeekZone.addEventListener('lostpointercapture'", script)
        self.assertIn("requestAnimationFrame(photoDetailVideoApplyPendingSeek)", script)
        self.assertIn("function photoDetailVideoScheduleHide", script)
        self.assertNotIn("function photoDetailVideoToggleFullscreen", script)
        self.assertNotIn("video.webkitEnterFullscreen", script)
        self.assertIn("new AbortController()", script)
        self.assertIn("document.addEventListener('visibilitychange'", script)
        self.assertIn(".photo-detail-video-media > video", css)
        self.assertIn(".photo-detail-video-controls", css)
        self.assertIn("#photo-detail-video-seek", css)
        self.assertIn("pointer-events: none", css)
        self.assertIn(".photo-detail-video-times", css)
        self.assertIn(".photo-detail-video-controls.scrubbing", css)
        self.assertIn("'pause':", icons)
        self.assertIn("'volume-2':", icons)
        self.assertIn("'volume-x':", icons)
        self.assertIn("'minimize-2':", icons)
        self.assertIn("if(photoDetailFormalEligible(job))", script)
        self.assertIn("renderDetailSkeleton=function(){if(photoDetailMobileMode()){photoDetailRenderLoading();return}", script)
        self.assertIn("function photoDetailRenderFormalState", script)
        self.assertIn("function photoDetailRenderLoadError", script)
        self.assertIn("function photoDetailRenderFailure", script)
        self.assertIn("function photoDetailHandleImportedAction", script)
        self.assertIn("if(action==='process'){photoDetailRenderActions();return}", script)
        self.assertIn("function openDetailLightbox(job,index){if(photoDetailFormalEligible(job))", script)
        self.assertNotIn("已切换到普通详情", script)
        self.assertIn("function photoDetailComparison", script)
        self.assertIn("function photoDetailLoadOriginal", script)
        self.assertIn("function photoDetailCommitPage", script)
        self.assertIn("function photoDetailPagingDuration", script)
        self.assertIn("function photoDetailPageGap", script)
        self.assertIn("function photoDetailRefreshChrome", script)
        self.assertIn("function photoDetailConfirmDelete", script)
        self.assertIn("function photoDetailLoadTaskContext", script)
        self.assertIn("function photoDetailEntrySequence", script)
        self.assertIn("function photoDetailAdoptEntry", script)
        self.assertIn("function photoDetailThumbPosition", script)
        self.assertIn("function photoDetailRotateSlots", script)
        self.assertNotIn("function photoDetailSpring", script)
        self.assertIn("function photoDetailReadTranslate", script)
        self.assertIn("function photoDetailPagerApply", script)
        self.assertIn("photoDetailUi.track.animate", script)
        self.assertIn("geometry.panel.animate", script)
        self.assertIn("photoDetailSheetCancelAnimation", script)
        self.assertNotIn("photoDetailGesture.locked", script)
        self.assertNotIn("sign*24", script)
        self.assertIn("function photoDetailCancelMotions", script)
        self.assertIn("function photoDetailOpenSheet", script)
        self.assertIn("function photoDetailInstallSheet", script)
        self.assertIn("function photoDetailSheetRest", script)
        self.assertIn("photoDetailPreview(version.src,128)", script)
        self.assertNotIn("photoDetailPreview(version.src,192)", script)
        self.assertIn("function photoDetailThumbRadius", script)
        self.assertIn("function photoDetailUpdateThumbProgress", script)
        self.assertNotIn("function photoDetailPreloadAdjacent", script)
        self.assertIn("function photoDetailElasticScale", script)
        self.assertNotIn("start.x*ratio", script)
        self.assertIn("photoDetailGesture.startZoom.scale*midpoint.distance/Math.max(1,photoDetailGesture.startDistance)", script)
        self.assertIn("scale=photoDetailElasticScale(rawScale,maximum)", script)
        self.assertIn("photoDetailElasticOffset(rawX", script)
        self.assertIn("function photoDetailRecoverInterruptedGesture", script)
        self.assertIn("scale<=1.08?{scale:1,x:0,y:0}", script)
        self.assertIn("if(event.isPrimary&&!photoDetailGesture.pointers.has(event.pointerId)&&photoDetailGesture.pointers.size)photoDetailRecoverInterruptedGesture()", script)
        self.assertIn("addEventListener('lostpointercapture',photoDetailPointerEnd", script)
        self.assertIn("photoDetailGesture.pointers.size>=2", script)
        self.assertIn("function photoDetailSettleZoom", script)
        self.assertIn("function photoDetailCaptureEntryTransition", script)
        self.assertIn("function photoDetailPixelSnapshot", script)
        self.assertIn("function photoDetailFinalizeEntryViews", script)
        self.assertIn("preserveEntrySource=key==='detail'", script)
        self.assertIn("function photoDetailCaptureExitTransition", script)
        self.assertIn("function photoDetailRunExitTransition", script)
        self.assertIn("function photoDetailStableTargetRect", script)
        self.assertIn("function photoDetailRectDistance", script)
        self.assertIn("duration:70,easing:PHOTO_DETAIL_EASING_STANDARD", script)
        self.assertIn("function photoDetailExitToHistory", script)
        self.assertIn("function photoDetailSaveHistoryTarget", script)
        self.assertIn("function photoDetailRememberContextOffsets", script)
        self.assertIn("function photoDetailCaptureTaskSeed", script)
        self.assertIn("photoDetailEntryTasks:[]", script)
        self.assertIn("photoDetailContextResolved=false", script)
        self.assertIn("state.photoDetailContextLoading=false", script)
        self.assertIn("state.photoDetailContextResolved=true", script)
        self.assertIn("state.photoDetailContextHasAfter=Boolean(context.has_after)", script)
        self.assertIn("function photoDetailExtendTaskContext", script)
        self.assertIn("function photoDetailMaybePrefetchTaskContext", script)
        self.assertIn("function photoDetailFinishPendingContext", script)
        self.assertIn("photoDetailContextPending:null", script)
        self.assertIn("state.photoDetailJobId='';state.photoDetailContextOriginId=''", script)
        self.assertIn("if(boundaryDirection)photoDetailRequestBoundaryPage(boundaryDirection)", script)
        self.assertIn("photoDetailRunEntryTransition(job)", script)
        self.assertIn("image.decode?.().catch", script)
        self.assertNotIn("image.decoding?.()", script)
        self.assertIn("console.error('[photo-detail] render failed'", script)
        self.assertIn("photoDetailPager.offset<=-metrics.width*.5", script)
        self.assertIn("!zoomed&&dx<0&&velocityX<=-.5", script)
        self.assertIn("edgeDistance-64", script)
        self.assertIn("Math.exp(-edgeDistance/20)", script)
        self.assertIn("photoDetailScheduleCommitRefresh", script)
        self.assertIn("requestIdleCallback", script)
        self.assertNotIn("function photoDetailPreloadNeighbors", script)
        self.assertIn("role','slider'", script)
        self.assertIn("function photoDetailSyncCompareGeometry", script)
        self.assertIn("comparison?.enabled?'compare-pending':'pan'", script)
        self.assertIn("photoDetailGesture.totalMove<8", script)
        self.assertIn("photoDetailGesture.startCompare+dx/Math.max(1,metrics.displayWidth)*100", script)
        self.assertIn("mode==='compare-pan'", script)
        self.assertIn("function photoDetailPanInertia", script)
        self.assertIn("function photoDetailStopZoomMotion", script)
        self.assertIn("function photoDetailMediaViewportRect", script)
        self.assertIn("parseFloat(getComputedStyle(media).bottom)", script)
        self.assertIn("window.visualViewport?.height||innerHeight", script)
        self.assertIn("transition.destination=destination", script)
        self.assertIn("photoDetailRectDistance(transition.destination,actual)>.35", script)
        self.assertIn("function photoDetailTrackVerticalGesture", script)
        self.assertIn("function photoDetailPrepareInfoGesture", script)
        self.assertIn("function photoDetailApplyVerticalExit", script)
        self.assertIn("function photoDetailCancelVerticalExit", script)
        self.assertIn("gesture.verticalArmed&&distance<=threshold*.25", script)
        self.assertIn("gesture.verticalCancelled=true", script)
        self.assertIn("commit=photoDetailGesture.verticalArmed", script)
        self.assertNotIn("commit=!cancelled&&photoDetailGesture.verticalArmed", script)
        self.assertIn("addEventListener('pointercancel',photoDetailPointerEnd", script)
        self.assertIn("addEventListener('lostpointercapture',photoDetailPointerEnd", script)
        self.assertIn("gestureTransition=", script)
        self.assertNotIn("function photoDetailVideoControlHit", script)
        self.assertIn("velocityY", script)
        self.assertIn("didDrag:false", script)
        self.assertIn("hadPinch:false", script)
        self.assertIn("edgeBrowseReady", script)
        self.assertIn("!didDrag&&!hadPinch&&total<=6", script)
        self.assertIn("else if(mode.startsWith('compare'))photoDetailPagerSettle()", script)
        self.assertIn("['contextmenu','selectstart','dragstart']", script)
        self.assertIn(".photo-detail-experience.immersive", css)
        self.assertIn("#view-detail.photo-detail-experience-active {", css)
        self.assertIn("height: 100dvh", css)
        self.assertIn("background: #000", css)
        self.assertIn("-webkit-touch-callout: none", css)
        self.assertIn(".photo-detail-sheet[open]", css)
        self.assertIn(".photo-detail-track", css)
        self.assertIn(".photo-detail-compare-glow", css)
        self.assertIn("--photo-media-bottom-reserve: clamp(24px,5dvh,40px)", css)
        self.assertIn(".vertical-exit-tracking", css)
        self.assertIn(".photo-detail-sheet.pull-ready", css)
        self.assertIn("var(--photo-compare-height,100%)", css)
        self.assertIn("mask-image: linear-gradient(to bottom,transparent,#000 7%,#000 93%,transparent)", css)
        self.assertNotIn(".photo-detail-compare-divider", css)
        self.assertIn('.photo-detail-page[data-photo-slot="2"]', css)
        self.assertIn("--photo-page-gap: 32px", css)
        self.assertIn("PHOTO_DETAIL_EASING_PAGING", script)
        self.assertIn(".photo-detail-delete-menu", css)
        self.assertIn("--photo-thumb-crop", css)
        self.assertIn("clip-path: inset(0 var(--photo-thumb-crop,8px)", css)
        self.assertNotIn("scale3d(.64,.94,1)", css)
        self.assertNotIn("clip-path: inset(1px 8px", css)
        self.assertIn(".photo-detail-sheet-grabber", css)
        self.assertIn(".photo-detail-sheet-dimmer", css)
        self.assertIn(".photo-detail-experience.motion-active", css)
        self.assertNotIn("height: 100dvh;\n  object-fit: contain", css)
        self.assertIn("grid-template-columns: repeat(var(--photo-action-count,5)", css)
        self.assertIn("height: 68dvh", css)
        self.assertIn("visibility: hidden", css)
        self.assertIn("--photo-float: rgba(9,22,39,.78)", css)
        self.assertIn("html.photo-detail-active", css)
        self.assertIn("contain: layout paint", css)
        self.assertIn("photoDetailSheetApply(dialog,translated,gesture.geometry)", script)
        self.assertIn("dragTargets=[header,grabber]", script)
        self.assertIn("photoDetailGesture.startMetrics||photoDetailFitMetrics", script)
        self.assertIn("touch-action: pan-y !important", css)
        self.assertIn("overflow-anchor: none", css)
        self.assertIn(".photo-detail-sheet.presented:not(.animating):not(.dragging)", css)
        self.assertIn(".photo-detail-action-group-left", css)
        self.assertIn(".photo-detail-action-group-right", css)
        self.assertIn("grid-template-rows: 66px minmax(0,1fr)", css)
        self.assertNotIn("scrollIntoView({behavior:matchMedia", script)
        self.assertNotIn("pull-ready .photo-detail-sheet-body", css)
        self.assertNotIn("gesture.axis==='manual-scroll'", script)
        self.assertIn("panel.focus({preventScroll:true})", script)
        self.assertIn("function photoDetailEffectiveCfg", script)
        self.assertIn("photo-detail-prompt-collapsible", script)
        self.assertIn("font-size: 12px", css)
        self.assertIn("cfg!==null&&cfg<=1", script)
        self.assertNotIn("grid-template-rows: auto minmax(0,1fr) 68px 66px", css)
        self.assertIn("@media (orientation: landscape) and (max-width: 1099px)", css)
        self.assertIn('grid-template-areas: "back left-actions heading right-actions rerun"', css)
        self.assertIn(".photo-detail-topbar::before", css)
        self.assertIn(".photo-detail-topbar::after", css)
        self.assertIn("width: clamp(360px,52vw,480px)", css)
        self.assertIn(".canvas-close-control", css)
        self.assertIn(".photo-detail-sheet-body :where(", css)
        self.assertIn(".photo-detail-entry-layer", css)
        self.assertIn(".photo-detail-entry-backdrop { z-index: 83", css)
        self.assertIn(".photo-detail-exit-backdrop", css)
        self.assertIn(".photo-detail-exit-target", css)
        self.assertIn("> :is(img,canvas)", css)
        self.assertIn(".entry-transition-active .photo-detail-stage { background: transparent; }", css)
        self.assertIn("photo-detail-entry-sharp", script)
        self.assertIn("transition.layer.append(sharp)", script)
        self.assertIn("transition.clone.animate(movement,options)", script)
        self.assertIn("sharp.animate(movement,options)", script)
        self.assertIn("const pending=target.decode?.()", script)
        self.assertIn("duration:340,easing:PHOTO_DETAIL_EASING_STANDARD", script)
        self.assertIn("entry-transition-settled", script)
        self.assertIn(".photo-detail-experience.entry-transition-settled { animation: none; }", css)
        self.assertIn("borderRadius:`${finalCloneRadius}px`", script)
        self.assertIn("photoDetailEntryClip(mid,radius*.42)", script)
        self.assertIn("target.classList.remove('photo-detail-exit-target')", script)
        self.assertIn("photoDetailThumbSeeds:new Map()", script)
        self.assertIn("state.photoDetailContextResolved=false", script)
        self.assertIn("state.photoDetailContextLoading=false", script)
        self.assertIn("state.detailJob&&!state.detailJob.shared_context?state.detailJob:job", script)
        self.assertIn("photoDetailLoadTaskContext(refocusJob,{radius})", script)
        self.assertIn("changedJob&&!state.photoDetailContextResolved&&!state.photoDetailContextLoading", script)
        self.assertIn("photoDetailPreview(version.src,128)", script)
        self.assertIn("previewSize=distance<=1?960:256", script)
        self.assertIn("photoDetailRenderSlots();photoDetailRenderThumbs()", script)
        self.assertNotIn("photoDetailRenderSlots({force:true});photoDetailRenderThumbs()", script)
        self.assertIn("timer=setTimeout(()=>{finish()},400)", script)
        self.assertNotIn("timer=setTimeout(finish,2200)", script)
        self.assertIn("duration:90,easing:PHOTO_DETAIL_EASING_STANDARD", script)
        self.assertIn("options={duration:320,easing:PHOTO_DETAIL_EASING_SPATIAL", script)
        self.assertIn("coverVersion=current.version?.kind==='final'", script)
        self.assertIn("sameCover=transition.coverVersion", script)
        self.assertIn("duration=sameCover?80:180", script)
        self.assertIn("target.animate([{opacity:0},{opacity:1}]", script)
        self.assertNotIn("setTimeout(begin,220)", script)
        self.assertIn("prefers-reduced-motion: reduce", css)

    def test_history_detail_uses_memory_snapshot_and_preview_images(self) -> None:
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "style.css").read_text(encoding="utf-8")
        self.assertIn("historyJobs:new Map()", script)
        self.assertIn("function rememberHistoryJob(job)", script)
        self.assertIn("const token=++state.detailLoadToken,cached=state.historyJobs.get(id)", script)
        self.assertIn("function renderDetailSkeleton()", script)
        self.assertIn("before.src=previewUrl(beforeSrc,960)", script)
        self.assertIn("after.src=previewUrl(afterSrc,960)", script)
        self.assertIn("responsivePreview(image,link.href", script)
        self.assertIn(".detail-skeleton", css)

    def test_running_detail_progressively_renders_metadata_and_results(self) -> None:
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        self.assertIn("function renderPendingResults(job)", script)
        self.assertIn("renderDetail(job);if(job.status==='completed'", script)
        self.assertIn("scheduleDetailPoll(id,1200", script)
        self.assertIn("function reconcileDetailResults(job)", script)
        self.assertIn("detailItemRenderSignature(item)", script)
        self.assertNotIn("正在同步最新状态…", script)
        self.assertIn("正在等待第一张结果图", script)

    def test_device_completion_inbox_and_compact_progress_capsule_are_present(self) -> None:
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "style.css").read_text(encoding="utf-8")
        self.assertIn('id="device-task-history"', html)
        self.assertIn('id="global-task-time"', html)
        self.assertIn('id="global-task-item"', html)
        self.assertIn("mobileImageTaskInboxV1", script)
        self.assertIn("function captureSubmittedImageTask", script)
        self.assertIn("/api/device-task-status", script)
        self.assertIn("function reconcileDeviceTasks", script)
        self.assertIn("function setGlobalTaskExpanded", script)
        self.assertIn("function queueClock", script)
        self.assertIn("function queueItemFraction", script)
        self.assertIn("function queueStepFraction", script)
        self.assertIn("function compactQueuePhase", script)
        self.assertIn("if(key==='sampling')return'采样中'", script)
        self.assertIn("task.queue_elapsed_seconds", script)
        self.assertIn("'--overall-progress'", script)
        self.assertIn("window.addEventListener('storage'", script)
        self.assertIn("prepareFluxUpscale=async function()", script)
        self.assertIn(".global-task.collapsed", css)
        self.assertIn("width:150px", css)
        self.assertIn("height:34px", css)
        self.assertIn(".global-task-metrics", css)
        self.assertIn(".global-task.keyboard-hidden", css)
        self.assertIn(".device-task-history-row", css)

    def test_global_task_capsule_drags_persists_and_peeks_from_either_wall(self) -> None:
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "style.css").read_text(encoding="utf-8")
        interface_css = (STATIC / "interface.css").read_text(encoding="utf-8")
        self.assertIn("mobileGlobalTaskPositionV1", script)
        self.assertIn("GLOBAL_TASK_PEEK_DELAY=3000", script)
        self.assertIn("function initGlobalTaskDrag", script)
        self.assertIn("function applyGlobalTaskPosition", script)
        self.assertIn("function scheduleGlobalTaskPeek", script)
        self.assertIn("bar.setPointerCapture(pointerId)", script)
        self.assertIn("Math.hypot(dx,dy)<4", script)
        self.assertIn("side=rect.left+rect.width/2", script)
        self.assertIn("event.target.closest('.global-task-stop')", script)
        self.assertIn("event.key===GLOBAL_TASK_POSITION_KEY", script)
        self.assertIn(".global-task.peeking.side-left", css)
        self.assertIn(".global-task.peeking.side-right", css)
        self.assertIn("var(--overall-progress)", css)
        self.assertIn("var(--global-task-progress-start,#879ff2)", css)
        self.assertIn("var(--global-task-progress-middle,#9cc8ff) var(--overall-progress)", css)
        self.assertIn("--global-task-progress-start: #879ff2", interface_css)
        self.assertIn("background-size: var(--overall-progress) 100%", interface_css)
        self.assertIn("content:\"\"; position:absolute; z-index:3; inset:0", css)
        self.assertIn(".global-task.peeking.failed::before", css)
        self.assertIn("width:44px; height:44px", css)
        self.assertIn("@keyframes global-task-peek-pulse", css)
        self.assertIn("phase=`${task.id}:${task.state}`", script)
        self.assertNotIn("phase=`${task.id}:${task.state}:${task.progress_phase}`", script)
        self.assertNotIn("phase=`${task.id}:${task.state}:${task.progress_phase_key", script)

    def test_active_history_placeholder_opens_pending_photo_detail(self) -> None:
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        interface_script = (STATIC / "interface.js").read_text(encoding="utf-8")
        css = (STATIC / "interface.css").read_text(encoding="utf-8")
        self.assertIn("function fetchActiveHistoryJobs", script)
        self.assertIn("api('/api/queue')", script)
        self.assertIn("mergeActiveHistoryJobs(jobs,active)", script)
        self.assertIn("function historyTaskPlaceholder", script)
        self.assertIn("function updateActiveHistoryPlaceholders", script)
        self.assertIn("function completedOwnGenerationIds", script)
        self.assertIn("function reconcileHistoryCards", script)
        self.assertIn("function historyReconcileTerminalCard", script)
        self.assertIn("function scheduleHistoryCompletionReconcile", script)
        self.assertIn("historyImageReady(nextImage)", script)
        self.assertNotIn("root.replaceChildren(fragment)", script)
        self.assertIn("canvas-history-card-updated", interface_script)
        self.assertIn("function addedOwnGenerationCount", script)
        self.assertIn("function photoDetailPendingJob", script)
        self.assertIn("function photoDetailRenderPending", script)
        self.assertIn("function photoDetailExpectedCount", script)
        self.assertIn("function photoDetailUpdateLiveTask", script)
        self.assertIn("function photoDetailUpdatePendingFrame", script)
        self.assertIn("frame.dataset.taskJobId!==jobId", script)
        self.assertIn("frame.dataset.taskRatio!==ratioKey", script)
        self.assertIn(
            "function photoDetailFormalEligible(job){return photoDetailMobileMode()}",
            script,
        )
        self.assertIn("if(photoDetailPendingJob(job)){photoDetailRenderPending(job)", script)
        self.assertIn(".history-task-placeholder", css)
        self.assertIn("@keyframes history-task-ambient-a", css)
        self.assertIn("@keyframes history-task-ambient-b", css)
        self.assertNotIn("history-task-placeholder-sweep", css)
        self.assertIn(".history-result-entering.history-result-ready", css)
        self.assertIn(".history-task-terminal", css)
        self.assertIn(".photo-detail-task-frame", css)
        self.assertIn("--photo-task-progress", css)
        self.assertNotIn(".photo-detail-task-indicator", css)
        self.assertIn("@keyframes photo-detail-task-develop", css)
        self.assertIn("@keyframes photo-detail-task-wash", css)
        self.assertIn("position: fixed; z-index: 2; top: var(--photo-safe-top); right: auto; left: 50vw", css)
        self.assertNotIn("inset: calc(54px + var(--photo-safe-top)) 0 calc(124px + var(--photo-safe-bottom))", css)
        self.assertIn(".photo-detail-experience.task-processing", css)

    def test_portrait_viewer_and_compact_history_controls_are_present(self) -> None:
        html = (STATIC / "index.html").read_text(encoding="utf-8")
        script = (STATIC / "app.js").read_text(encoding="utf-8")
        css = (STATIC / "style.css").read_text(encoding="utf-8")
        self.assertIn('id="media-zoom-width"', html)
        self.assertIn('id="detail-zoom-width"', html)
        self.assertIn('id="detail-inspector-toggle"', html)
        self.assertIn("function viewerMetrics", script)
        self.assertIn("function fitViewerWidth", script)
        self.assertIn("zoom.actual*4", script)
        self.assertIn("viewerZoom[kind].scale/1.2", script)
        self.assertIn("viewerZoom[kind].scale*1.2", script)
        self.assertIn("transition:transform .12s ease-out", css)
        self.assertNotIn("touch-action:manipulation", css)
        self.assertIn("grid-template-rows:auto 214px", css)
        self.assertIn("function renderDetailParameters", script)
        self.assertIn("history-param-primary", script)
        self.assertIn(".detail-parameter-panel", css)
        self.assertIn('class="detail-title-row"', html)
        self.assertIn("detail-seed-disclosure", script)
        self.assertIn(".detail-lora-list", css)
        self.assertIn(".detail-lightbox.inspector-collapsed", css)
        self.assertIn("function imageMediaSemantics(job={})", script)
        self.assertIn("function sourceCompareState(job)", script)
        self.assertIn("subject=imageMediaSemantics(job).compareSubject", script)
        self.assertIn("button.textContent=comparison.enabled?`关闭${subject}对比`:`开启${subject}对比`", script)
        self.assertIn("defaultEnabled=job.parameters?.reference_mode!=='identity'", script)
        self.assertIn("function modelParameterLabel", script)
        self.assertIn("modelParameterLabel('krea_model'", script)
        self.assertIn("modelParameterLabel('h3_model'", script)
        self.assertIn("job.source_image&&showReference?'source-latest'", script)
        self.assertIn("function installComparisonActivity", script)
        self.assertIn("opacity:.02;pointer-events:none", css)
        self.assertIn(".compare.mobile-controls-visible .compare-range", css)
        self.assertIn(".pre-compare:hover .compare-range", css)
        self.assertIn("@media(max-width:1099px){.pre-compare .compare-range{opacity:.7;pointer-events:auto}", css)


if __name__ == "__main__":
    unittest.main()
